masglobal:
  datasource:
    api-uri: http://masglobaltestapi.azurewebsites.net/api
spring:
  datasource:
    url: jdbc:mysql://localhost:3406/masglobal
    username: payroll
    password: m4sgl0b4l
  jpa:
    hibernate:
      ddl-auto: create