masglobal:
  datasource:
    api-uri: http://masglobaltestapi.azurewebsites.net/api
spring:
  datasource:
    url: jdbc:mysql://localhost:3406/payroll
    username: payroll
    password: d0ck3r1z3
  jpa:
    hibernate:
      ddl-auto: create